### ISSUE TITLE
Will you please help me

### ISSUE THREAD

**Issue by kunaldodiya** [amitavroy/library#1]
will you please help me in my electron project.. i have no idea about Electron.. i have a working website in nuxt+adonisjs(AdoNuxt) that i want to convert in desktop app.. but i am stuck in middle. if you can contribute and help a bit it would be a great help :)

https://github.com/kunaldodiya/streamly

**Comment by amitavroy** [comment]
I am not sure on what exactly you need to do. Share the same on my email
and let me see if I can find time to help you out.

Thanks
Amitav Roy
Mobile: 9820215537
Email: reachme@amitavroy.com

**Comment by kunaldodiya** [comment]
Tnx a lot.  I am sending you the detail and repo.  Tnx a lot again for helping
